---
- name: "Docker container deployment playbook"
  hosts: localhost
  gather_facts: yes
  become: true
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Docker
      community.docker.docker_container:
        name: mydata
        image: gitlab.example.com:4567/root/cdaas-demo-app:development
        ports:
        - "8888:8080"
