---
- name: "Docker container deployment playbook"
  hosts: localhost
  gather_facts: yes
  become: true
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Docker
      community.docker.docker_container:
        name: "{{ lookup('env', 'ARTIFACT_NAME') }}"
        image: "{{ lookup('env', 'IMAGE_TAG') }}"
        ports:
        - "8888:8080"
